sudo: required

services:
  - docker

language: generic

before_install:
  - openssl aes-256-cbc -K $encrypted_4c33bcc26b3b_key -iv $encrypted_4c33bcc26b3b_iv -in kubeconfig.enc -out kubeconfig -d
  - KUBE_LATEST_VERSION="v1.14.1"
  - HELM_LATEST_VERSION="v2.13.1"
  - HELM=https://storage.googleapis.com/kubernetes-helm/helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz
  - KUBECTL=https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/amd64/kubectl
  - curl -L ${KUBECTL} -o $PWD/kubectl
  - curl -L ${HELM} | tar xzO linux-amd64/helm > $PWD/helm
  - chmod +x $PWD/helm $PWD/kubectl
  - export -p PATH=$PATH:$PWD

jobs:
  include:
    - stage: deploy
      name: Create the necessary infrastructure to support pipeline deployments
      if: branch = master and type != pull_request
      script:
        - export KUBECONFIG=$PWD/kubeconfig
        - helm template -f $PWD/values.yaml $PWD/kubernetes | kubectl apply -f -
