apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
data:
  general.recipient_delimiter: {{ .Values.general.recipient_delimiter }}
  general.postmaster: {{ quote (.Values.general.postmaster | replace "__DOMAIN__" .Values.server.domain) }}

  server.domain: "{{ .Values.server.domain }}"
  server.hostname: {{ quote (.Values.server.hostname | replace "__DOMAIN__" .Values.server.domain) }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-panel
  namespace: {{ .Values.namespace }}
data:
  # These values are used to initialise the administration access (You should change them immediately)
  ADMIN_USERNAME: "{{ .Values.admin.username }}"
  ADMIN_PASSWORD: "{{ .Values.admin.password }}"
  ADMIN_EMAIL: {{ quote (.Values.admin.email | replace "__DOMAIN__" .Values.server.domain) }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: connection-map
  namespace: {{ .Values.namespace }}
data:
  POSTFIX_HOSTNAME: {{ quote (.Values.postfix.hostname | replace "__NAMESPACE__" .Values.namespace) }}
  POSTFIX_PORT: "{{ .Values.postfix.port }}"

  LMTP_HOSTNAME: {{ quote (.Values.lmtp.hostname | replace "__NAMESPACE__" .Values.namespace) }}
  LMTP_PORT: "{{ .Values.lmtp.port }}"

  OPENDKIM_HOSTNAME: {{ quote (.Values.opendkim.hostname | replace "__NAMESPACE__" .Values.namespace) }}
  OPENDKIM_PORT: "{{ .Values.opendkim.port }}"

  RSPAMD_HOSTNAME: {{ quote (.Values.rspamd.hostname | replace "__NAMESPACE__" .Values.namespace) }}
  RSPAMD_PORT: "{{ .Values.rspamd.port }}"

  REDIS_HOSTNAME: {{ quote (.Values.redis.hostname | replace "__NAMESPACE__" .Values.namespace) }}
  REDIS_PORT: "{{ .Values.redis.port }}"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: database-common
  namespace: {{ .Values.namespace }}
data:
  DATABASE_HOSTNAME: {{ quote (.Values.database.hostname | replace "__NAMESPACE__" .Values.namespace) }}
  DATABASE_PORT: "{{ .Values.database.port }}"
  DATABASE_NAME: {{ quote (.Values.database.name | replace "__NAMESPACE__" .Values.namespace | replace "-" "_") }}
  DATABASE_ENCODING: "{{ .Values.database.encoding }}"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: database-root
  namespace: {{ .Values.namespace }}
data:
  DATABASE_USERNAME: "root"
  DATABASE_PASSWORD: "{{ .Values.database.root_password }}"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: database-read
  namespace: {{ .Values.namespace }}
data:
  DATABASE_USERNAME: "{{ .Values.database.read_username }}"
  DATABASE_PASSWORD: "{{ .Values.database.read_password }}"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: database-write
  namespace: {{ .Values.namespace }}
data:
  DATABASE_USERNAME: "{{ .Values.database.write_username }}"
  DATABASE_PASSWORD: "{{ .Values.database.write_password }}"
---

