apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
data:
  database.hostname: {{ quote (.Values.database.hostname | replace "__NAMESPACE__" .Values.namespace) }}
  database.port: "{{ .Values.database.port }}"
  database.root_password: "{{ .Values.database.root_password }}"
  database.name: {{ quote (.Values.database.name | replace "__NAMESPACE__" .Values.namespace | replace "-" "_") }}
  database.encoding: "{{ .Values.database.encoding }}"

  # These values are used to initialise the administration access (You should change them immediately)
  admin.admin_username: "{{ .Values.admin.username }}"
  admin.admin_password: "{{ .Values.admin.password }}"
  admin.admin_email: {{ quote (.Values.admin.email | replace "__DOMAIN__" .Values.server.domain) }}

  general.recipient_delimiter: {{ .Values.general.recipient_delimiter }}
  general.postmaster: {{ quote (.Values.general.postmaster | replace "__DOMAIN__" .Values.server.domain) }}

  server.domain: "{{ .Values.server.domain }}"
  server.hostname: {{ quote (.Values.server.hostname | replace "__DOMAIN__" .Values.server.domain) }}

  postfix.hostname: {{ quote (.Values.postfix.hostname | replace "__NAMESPACE__" .Values.namespace) }}
  postfix.port: "{{ .Values.postfix.port }}"

  lmtp.hostname: {{ quote (.Values.lmtp.hostname | replace "__NAMESPACE__" .Values.namespace) }}
  lmtp.port: "{{ .Values.lmtp.port }}"

  opendkim.hostname: {{ quote (.Values.opendkim.hostname | replace "__NAMESPACE__" .Values.namespace) }}
  opendkim.port: "{{ .Values.opendkim.port }}"

  rspamd.hostname: {{ quote (.Values.opendkim.hostname | replace "__NAMESPACE__" .Values.namespace) }}
  rspamd.port: "{{ .Values.rspamd.port }}"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: database-common
  namespace: {{ .Values.namespace }}
data:
  DATABASE_HOSTNAME: {{ quote (.Values.database.hostname | replace "__NAMESPACE__" .Values.namespace) }}
  DATABASE_PORT: "{{ .Values.database.port }}"
  DATABASE_NAME: {{ quote (.Values.database.name | replace "__NAMESPACE__" .Values.namespace | replace "-" "_") }}
  DATABASE_ENCODING: "{{ .Values.database.encoding }}"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: database-root
  namespace: {{ .Values.namespace }}
data:
  DATABASE_USERNAME: "root"
  DATABASE_PASSWORD: "{{ .Values.database.root_password }}"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: database-read
  namespace: {{ .Values.namespace }}
data:
  DATABASE_USERNAME: "{{ .Values.database.read_username }}"
  DATABASE_PASSWORD: "{{ .Values.database.read_password }}"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: database-write
  namespace: {{ .Values.namespace }}
data:
  DATABASE_USERNAME: "{{ .Values.database.write_username }}"
  DATABASE_PASSWORD: "{{ .Values.database.write_password }}"
---

